### ISSUE TITLE
Standalone on rpi 

### ISSUE THREAD

**Issue by DerDoubleD** [yllibed/Zigbee2MqttAssistant#152]
is it possible to run it standalone on an rpi without docker or enething else

**Comment by carldebilly** [comment]
Yes it is. It's just so easier to run it using docker because you don't have to find the right runtime.

I suppose you want to run Linux on your RP...

# The simple method
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

# The hard core method
You can see how the dockerfile are built...  By example, for aspnet-netcore3.0, it's https://github.com/dotnet/dotnet-docker/blob/master/3.0/aspnet/alpine3.9/amd64/Dockerfile which is based on https://github.com/dotnet/dotnet-docker/blob/master/3.0/runtime/alpine3.9/amd64/Dockerfile, which is based on https://github.com/dotnet/dotnet-docker/blob/master/3.0/runtime-deps/alpine3.9/amd64/Dockerfile
