### ISSUE TITLE
Anyone running on RPI Zero W?

### ISSUE THREAD

**Issue by mlava** [yllibed/Zigbee2MqttAssistant#174]
I have had huge issues trying to get Z2MA up and running?

Can anyone confirm they have it running on a Pi Zero W?

**Comment by carldebilly** [comment]
I don't have this board to test it, but according to Wikipedia https://en.wikipedia.org/wiki/Raspberry_Pi the CPU is using the `ARMv6Z` instruction set.

To run `dotnet core`, `armv7` is required (`armv8`+ for 64 bits).  **So that's mean it won't work on RP-Zero or RP-Zero-W**.  Sorry.

I'll update the documentation on the README accordingly.

**Comment by mlava** [comment]
Ok, thanks.
At least I'm not going crazy...
