### ISSUE TITLE
Add support for OTA updates

### ISSUE THREAD

**Issue by carldebilly** [yllibed/Zigbee2MqttAssistant#184]
Add support for new Z2M OTA feature...
https://github.com/Koenkk/zigbee2mqtt/issues/2921

**Comment by XRyu** [comment]
Would love to see this too 👍

**Comment by netweaver1970** [comment]
One vote up from me too :)

**Comment by koenonline** [comment]
Perfect, looking forward to this feature!! Thx for all the good work👍

**Comment by carldebilly** [comment]
Thanks @magpern for the PR.  But I saw few things which need to be fixed: (I merged it too quickly because I was excited to see it working)
* The `update_available` is not a component, should be in the left-hand section of the list
* I don't see anything appearing in the device detail page, even when an update is available for a device.

**Comment by magpern** [comment]
> Thanks @magpern for the PR. But I saw few things which need to be fixed: (I merged it too quickly because I was excited to see it working)
> 
> * The `update_available` is not a component, should be in the left-hand section of the list
> * I don't see anything appearing in the device detail page, even when an update is available for a device.

@carldebilly I first looked at the code yesterday and started changing it. It is actually my first real contribution to the OpenSource community and I am so glad it is .NET, something I have worked with for years!

The exact architecture of the code I did not figure out. I figured you take some data from the Homeassistant topic and some data from the zigbee2mqtt topic.
To mee, taking data from the Homeassistant topic feels wrong, since zigbee2mqtt is not a homeassistant only application, you coud be running Domiticz or something else. But that is another story.

The `update_available` is known as a `binary_sensor` in homeassistant. This is what you use today to show the capabilities of the device, but if you don't have homeassistant you cannot rely on this entity for the OTA update. And it is only, "this device supports OTA update" no other info is available in this topic.

But looking at the `zigbee2mqtt\<friendlyname>` here the real information about the OTA update comes. It looks like this:

`{"state":"ON","linkquality":54,"brightness":254,"color_temp":370,"color":{"x":0.4599,"y":0.4106},"update_available":false}`

It the `update_available` is present, it supports OTA update
if the `update_available` is false, the device is up to date
if the `update_available` is true, a new firmware is available
If the `update_available` is missing, the device does not support OTA update, and it will not show in Z2MA

It is when this information is recieved by Z2MA that the OTA update is shown (if the device supports it)

Currently, this update requires the Z2M-dev, since this feature in Z2M is just a few weeks old, but the fix is compatible with Z2M stable too (you will see nothing new, if you run Z2M stable).

The most common devices that supports update are the IKEA Tradfri devices.

**Comment by magpern** [comment]
About the left hand side component badge, that is not me. Here is a picture of the original Z2MA
It's as I worte above, Z2M has implemented the `update_available` as a binary_senor device

![image](https://user-images.githubusercontent.com/6589760/75573677-9ff03780-5a5d-11ea-9322-53e31db51215.png)

in Homeassistant it looks like this
![image](https://user-images.githubusercontent.com/6589760/75573931-2573e780-5a5e-11ea-9d8f-21811e6ca6e1.png)

**Comment by carldebilly** [comment]
@magpern

## About Home Assistant topics
You're right.  That's why there's a PR to fix this on Z2M itself since a while: https://github.com/Koenkk/zigbee2mqtt/pull/2692  -- my goal is definitely to remove this dependency: it's causing problems.

## About the component
You're right too..  it's a new compoenent from Z2M, so it's totally valid :-) I though it was something you added.  That's not the case.

... I'm at work right now.  I'll check that during the weekend.  Thanks again for the contribution and don't hesitate to make more!

**Comment by magpern** [comment]
@carldebilly close?

**Comment by carldebilly** [comment]
You're right ;-)
