### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pgollor** [yllibed/Zigbee2MqttAssistant#195]
I use a fresh docker installation and the memory usage increases with every site refresh in the browser.

**Comment by magpern** [comment]
@pgollor I did a memory analysis of the application, and I think you are right. On every refresh the memory grown, in my case 0.2 MB. I think it might be related to the device images, because on the first analysis it keeps a lot of byte arrays in memory.
Nice thing is that when you force a garbage collection, the memory is collected - which usually means it can me fixed. How? Don't know at this point.

In the picture, then the graph starts to go up, this is me hitting refresh many times.
![image](https://user-images.githubusercontent.com/6589760/75610039-1f3d4400-5b0e-11ea-836d-8415e88d54c8.png)

**Comment by magpern** [comment]
Duplicate of #32 or atleast very related

**Comment by pgollor** [comment]
Sorry for the dublicate entry. So we can close this issue and keep #32 and hope findind a solution for that. Becaus i want to use the docker container on a raspberry pi with very limited memory.
