### ISSUE TITLE
[BUG] "update_available" badge persists after successfully updating

### ISSUE THREAD

**Issue by CodeFinder2** [yllibed/Zigbee2MqttAssistant#204]
I've updated 6 devices (plugs and bulbs) using the new OTA feature but the "update_available" component/badge is still being shown in the device list next to each updated device (rightmost column). Z2M and HA correctly report "update_available: false" so I assume it's a Z2MA bug (update of that badge missing?).

I've already restarted Z2M w/o success.

## Installation
 - Version of Zigbee2Mqtt: 1.11.0
 - Version of Zigbee2MqttAssistant: dev, 0.3.145 (0.3.145+Branch.master.Sha.7f6f10bc4855cba9870fd0d08ece33148f303ea9) 
 - Installation type (HASS.IO, Docker...): Hassio
 - Docker version + CPU type (amd64, arm arm64...): arm64

**Comment by magpern** [comment]
@CodeFinder2 this is not a bug, it is by design. The `update_available` badge indicates that this device has the ability to update it firmware, not that there is a new firmware available.

Unfortunately, this is the implementation in the zigbee2mqtt software. It registeres a `binary_sensor`  for each device that is able to update its firmware. This binary sensor is the reason for the badge. This sensor is under the `Homeassistant` topic

**Comment by CodeFinder2** [comment]
That makes perfectly sense, thanks for clarifying!

Maybe we should simply remove that badge completely and inform about available updates somewhere else as you already suggested in #206 . :sunglasses:
