### ISSUE TITLE
OTA Update Button

### ISSUE THREAD

**Issue by EdwardChamberlain** [yllibed/Zigbee2MqttAssistant#296]
**Is your feature request related to a problem? Please describe.**
OTA updates via Zigbee2Mqtt are supported for a small range of products. It would be nice to have a button that can be used to update devices rather than having to send the MQTT message.

**Describe the solution you'd like**
A button on the devices page that says "Update"

**Comment by magpern** [comment]
@EdwardChamberlain Do you mean this?
![image](https://user-images.githubusercontent.com/6589760/86516007-8a30bb80-be1d-11ea-91f4-d563721663a5.png)
and this?
![image](https://user-images.githubusercontent.com/6589760/86516012-9a489b00-be1d-11ea-9ce1-4c8ecd685ad3.png)

**Comment by EdwardChamberlain** [comment]
Perhaps this is a bug then since: 
![image](https://user-images.githubusercontent.com/7659338/86516223-bac12700-be16-11ea-8f4f-689825f722c9.png)
There is no update firmware button.

**Comment by magpern** [comment]
@EdwardChamberlain 
It only appears if a firmware is available and the current firmware is out of date.
If you click on the "Office Desk Lamp" row, you will see a "Firmware is up-to-date" or a "Update is available"
If you see neither, the device has not yet reported its firmware version to zwave2mqtt (the homeassistant topic)

**Comment by EdwardChamberlain** [comment]
@magpern Thats interesting since the `update_available` boolean is true but I dont see the "Firmware is up-to-date" or a "Update is available"

**Comment by magpern** [comment]
@EdwardChamberlain 
To me, it looks like you are running on a very very old version of zigbee2mqttAssistant.
The 'update_available' "badge" was removed long time ago and replaced with an OTA feature

Please update to latest Z2MA

**Comment by jcarvalho** [comment]
I'm getting the same issue on build `0.3.175+Branch.master.Sha.f1dc298d292590e077def97c9aa0cd4924dfbb11`.

Previously, I was running Z2MA as a Hass.io addon, and the button was indeed available, but I never saw it again after moving to running Z2MA directly on Docker.

**Comment by magpern** [comment]
@jcarvalho  Well, I assure you.. it is there.
I am running on the same version, and I am just updating 10 devices (this topic got my attention to do it)

This is what I run:
![image](https://user-images.githubusercontent.com/6589760/86521272-caf4f880-be4e-11ea-8544-eb1f99842aa8.png)

The update feature is a little cunning. The update information is not fetched directly on start. It comes when it comes. It is somewhat magically delayed. It appears when Z2M fetches the full info of the device and writes it to homeassistant mqtt.

Since we are running the same version, and also in docker, we should run on the same code base.
Do you know if your device needs update? (you can see this in home assistant, it says "Update avalable: ON" or as a check-box-icon with this data
![image](https://user-images.githubusercontent.com/6589760/86521326-861d9180-be4f-11ea-8090-622baba2e8d9.png)

**Comment by jcarvalho** [comment]
Ah, I'm sorry, you're totally right. I guess that when Z2MA was deployed in Hassio, its lifecycle was tied to that of Home Assistant, so the `update_available` property was always set.

Thanks for the great work, and once again, sorry for the confusion!

**Comment by carldebilly** [comment]
@magpern, do you suggest there's a bug in Z2M? I noticed this problem too but never got time to investigate it.

**Comment by magpern** [comment]
> @magpern, do you suggest there's a bug in Z2M? I noticed this problem too but never got time to investigate it.

No, no bug. Problem was running on old code.
