### ISSUE TITLE
Enchancement: Pairing timer

### ISSUE THREAD

**Issue by ciotlosm** [yllibed/Zigbee2MqttAssistant#99]
Besides the current "enable joining" button, there should be an extra button (which I recommend making as default) to enable joining only for a limited time (most of the gateways do this). This would reduce the risk of people forgetting to turn it off, or turning it off a few days later when they remember/check something. 

I think there should be two buttons:
- Short timer - with description for joining one device - Usable when adding new things to your setup
- Long timer - with description for re-doing your setup - Usable when starting from scratch or rebuilding a larger installation

A button to enable this without a timer should be hidden in a more "advanced" section. 

Potential problems: Memory leaks due to timer.

**Comment by carldebilly** [comment]
I was planning this feature too... but there's a problem with the "timer button"... because there's many scenarios where the timer won't work...
* If you restart Z2MA
* If you are using another mean to activate the join...

My solution would be to activate a `allowJoinTimeout` in the settings which would be activated no matter how you activated the feature. What do you think?

**Comment by ciotlosm** [comment]
For posterity

Use cases:

1. Start pairing, wait time and stop
    - send enable pairing
    - start timer
    - timer finished
    - app disables pairing

2. Start paring but stop before timer
    - send enable pairing
    - start timer
    - manual disable pairing
    - cancel timer

3. Someone sends pairing request
    - Listen on mqtt
    - pairing request recevied from elsewhere
    - start timer
    - timer finished
    - app disables pairing

4. Someone stops pairing remove
    - send enable pairing
    - start timer
    - stop pairing recevied
    - cancel timer

5. Restart container during pairing
    - container starts
    - container asks status from z2m
    - container starts timer if pairing in progress
    - normal flow continues

5. Start container (normal start)
    - container starts
    - container checks if pairing in progree
    - if no pair in progress, do nothing

6. Container is running, pairing in progress, user restarts z2m
    - pair started
    - timer started
    - user restarts z2m (has pairing by default off) - any way to check stop status?
    - z2m starts
    - z2m sends status
    - cancel timer  (do not send pairing stop)

**Comment by carldebilly** [comment]
1. ✅ It works.
2. ✅ It work, the timer stopped as soon it's going back to off
3. ✅ It works the same way as #1 - because the timer is started when listening from MQTT
4. ✅ Similar to #2
5. ✅ Tested and it work
6. ✅
7. ✅ Not tested, but it should work. The Z2MA may send a turn off request if the timer expires while Z2M is offline. Not really a problem.

@ciotlosm Thanks!
